# playbooks/windows_info.yml
---
- name: Info Windows
  hosts: windows
  gather_facts: yes

  tasks:
    - name: Verificar uptime
      win_shell: (Get-Date) - (gcim Win32_OperatingSystem).LastBootUpTime
      register: uptime



    - name: Criar diretório C:\Temp
      win_file:
        path: C:\Temp
        state: directory

    - name: Criar arquivo de teste
      win_copy:
        content: "AWX funcionando no Windows!"
        dest: C:\Temp\awx_teste.txt
